cmd.hide('everything')
cmd.show('spheres', 'name CA or name N')
cmd.set('sphere_scale', 0.7)
cmd.get_sasa_relative('all', state=1, vis=0, var='b')
cmd.select('core', '(name CA or name N) and b < 0.17')
cmd.select('surface', '(name CA or name N) and b > 0.17')
cmd.color('salmon', 'core')
cmd.color('skyblue', 'surface')

# Core–core edges (solid, thick)
cmd.dist('core_core_edges', 'core', 'core', 8.5)
cmd.hide('labels', 'core_core_edges')
cmd.color('salmon', 'core_core_edges')
cmd.show('lines', 'core_core_edges')
cmd.set('dash_width', 5, 'core_core_edges')
cmd.set('dash_gap', 0, 'core_core_edges')

# Surface–surface edges (solid, thick)
cmd.dist('surface_surface_edges', 'surface', 'surface', 8.5)
cmd.hide('labels', 'surface_surface_edges')
cmd.color('skyblue', 'surface_surface_edges')
cmd.show('lines', 'surface_surface_edges')
cmd.set('dash_width', 4, 'surface_surface_edges')
cmd.set('dash_gap', 0, 'surface_surface_edges')

# Core–surface edges (dashed black)
cmd.dist('core_surface_edges', 'core', 'surface', 8.5)
cmd.hide('labels', 'core_surface_edges')
cmd.color('black', 'core_surface_edges')
cmd.show('dashes', 'core_surface_edges')
cmd.set('dash_width', 4, 'core_surface_edges')
cmd.set('dash_gap', 0.46, 'core_surface_edges')
cmd.set('dash_length', 0.16, 'core_surface_edges')

cmd.deselect()

